#!/usr/bin/python3
"""
Starts the osbuild-image-test executable asking it to filter its tests based on
current machine architecture and distribution.
"""

import subprocess
import configparser
import platform
import sys
from subprocess import CalledProcessError

OS_RELEASE_PATH = "/etc/os-release"

config = configparser.ConfigParser()
with open(OS_RELEASE_PATH, 'r', encoding='utf-8') as f:
    config_string = '[DEFAULT]\n' + f.read()
config.read_string(config_string)
distro = f"{config.get('DEFAULT', 'ID')}-{config.get('DEFAULT', 'VERSION_ID')}"
distro = distro.replace('"', '')

print(f"Running the osbuild-image-test for arch {platform.machine()} and "
      f"distribution {distro}")

command = ["tools/osbuild-image-test",
           f"--arch={platform.machine()}",
           f"--distro={distro}",
           "--generator-mode"]

pa_exec = sys.argv[1] if len(sys.argv) > 1 else None
if pa_exec:
    total = int(pa_exec.split("/")[1])
    part = int(pa_exec.split("/")[0])
    command.append(f"--instance-number={part}")
    command.append(f"--total-number-of-instances={total}")

print(" ".join(command), flush=True)
try:
    subprocess.run(command, check=True)
except CalledProcessError as e:
    print(e, file=sys.stderr)
    sys.exit(1)
