#!/usr/bin/python3
"""
Starts the osbuild-image-test executable asking it to filter its tests based on
current machine architecture and distribution.
"""

import subprocess
import configparser
import platform
import sys
from subprocess import CalledProcessError

OS_RELEASE_PATH = "/etc/os-release"

config = configparser.ConfigParser()
with open(OS_RELEASE_PATH, 'r', encoding='utf-8') as f:
    config_string = '[DEFAULT]\n' + f.read()
config.read_string(config_string)
distro = f"{config.get('DEFAULT', 'ID')}-{config.get('DEFAULT', 'VERSION_ID')}"
distro = distro.replace('"', '')
distro = distro.replace('.', '')

print(f"Running the osbuild-image-test for arch {platform.machine()} and "
        f"distribution {distro}")

try:
    subprocess.run(["tools/osbuild-image-test",
                    f"--arch={platform.machine()}",
                    f"--distro={distro}",
                    "--generator-mode"],
                    check=True)
except CalledProcessError:
    sys.exit(1)
