#!/usr/bin/python3
"""
Import Composer image tests
"""

import argparse
import json
import os
import pathlib
from typing import Iterator, Tuple, Dict, List, Any, Union

import yaml


RESET = "\033[0m"
GREEN = "\033[32m"
BOLD = "\033[1m"
RED = "\033[31m"
YELLOW = "\033[33m"


def list_tests(source: Union[str, pathlib.Path]) -> Iterator[Tuple[str, str]]:
    for entry in os.scandir(source):
        if not entry.is_file():
            continue
        if not entry.name.endswith(".json"):
            continue

        name = entry.name[:-5]
        fullpath = os.path.join(source, entry.name)
        yield name, fullpath


def load_test(name: str, fullpath: Union[str, pathlib.Path], filters: Dict[str, List[str]]) -> Dict[str, Any]:
    with open(fullpath, "r", encoding="utf-8") as f:
        data = json.load(f)

    manifest = data.get("manifest")
    if not manifest:
        raise ValueError("no manifest")

    req = data.get("compose-request")
    if not req:
        raise ValueError("no compose-request")

    if req["distro"] not in filters or req["arch"] not in filters[req["distro"]]:
        return {}

    test = {
        "id": name,
        "desc": {
            "distro": req["distro"],
            "arch": req["arch"],
            "image-type": req["image-type"],
            "filename": req["filename"]
        },
        "manifest": data["manifest"],
        "image-info": data.get("image-info"),
    }

    return test


def export_test(test: Dict, target: Union[str, pathlib.Path], manifest_only: bool) -> None:
    name = test["id"]
    fullpath = os.path.join(target, name + ".json")
    if manifest_only and os.path.exists(fullpath):
        # load existing
        with open(fullpath, "r", encoding="utf-8") as f:
            base = json.load(f)
        base["manifest"] = test["manifest"]
        test = base
    with open(fullpath, "w", encoding="utf-8") as f:
        json.dump(test, f, indent=2)


def report_ignoring(name: str, reason: str, verbosity: int = 1) -> None:
    if verbosity < 1:
        return

    if verbosity == 1:
        print(".", end="", flush=True)
    else:
        print(f"{YELLOW} SKIP  {reason} {RESET}{name}", flush=True)


def report_import(test: Dict, verbosity: int = 1) -> None:
    if verbosity < 1:
        return

    if verbosity == 1:
        print(".", end="", flush=True)
    else:
        print(f"{GREEN} OK   {RESET} {test['id']}", flush=True)


def report_failure(name: str, reason: str, verbosity: int = 1) -> None:
    if verbosity < 1:
        return

    if verbosity == 1:
        print(f"{RED}F{RESET}", end="", flush=True)
    else:
        print(f"{RED}FAIL {RESET} {name}: {reason}")


def parse_distro(ci_file: Union[str, pathlib.Path]) -> Dict[str, List[str]]:
    filters: Dict[str, List[str]] = {}
    if ci_file:
        with open(ci_file, "r", encoding="utf-8") as f:
            data = yaml.load(f, Loader=yaml.Loader)
            runners = data["Image-info-build"]["parallel"]["matrix"]
            for runner in runners:
                for machine_id in runner["RUNNER"]:
                    flavor = machine_id.split("/")[-1]
                    arch = flavor.split("-")[-1]
                    distro = ""
                    if "fedora" in flavor:
                        distro = f"fedora-{flavor.split('-')[1]}"
                    elif "centos" in flavor:
                        distro = f"centos-{flavor.split('-')[2]}"
                    elif "rhel" in flavor:
                        distro = f"rhel-{flavor.split('-')[1].replace('.', '')}"
                    else:
                        raise ValueError(f"unknown distribution {flavor}")
                    if distro in filters:
                        filters[distro].append(arch)
                    else:
                        filters[distro] = [arch]
    return filters

def parse_db_ignore(db_ignore_file: Union[str, pathlib.Path]) -> List[str]:
    with open(db_ignore_file, "r", encoding="utf-8") as f:
        return f.read().splitlines()

def main():
    parser = argparse.ArgumentParser(description="osbuild image tests")
    parser.add_argument(
        "SOURCE",
        metavar="DIRECTORY",
        type=os.path.abspath,
        help="directory where test cases are imported from")
    parser.add_argument(
        "TARGET",
        metavar="DIRECTORY",
        type=os.path.abspath,
        default=None,
        help="directory where test cases are exported to")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="do not export test cases"
    )
    parser.add_argument(
        "--manifest-only",
        action="store_true",
        default=False,
        help="Only import the manifests from composer"
    )
    parser.add_argument(
        "--filter-with-ci-distros",
        type=os.path.abspath,
        default=None,
        help="filter the importations from composer based on the distros coming from CI yml file"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--verbose",
        dest="verbosity",
        action="count",
        default=1,
        help="increase verbosity")
    group.add_argument(
        "--quiet",
        action="store_const",
        const=0,
        dest="verbosity",
        help="suppress output")
    parser.add_argument(
        "--db-ignore",
        type=os.path.abspath,
        default=None,
        help="A file containing one per line file names not to import")

    args = parser.parse_args()

    db_ignore = parse_db_ignore(args.db_ignore)

    filters = parse_distro(args.filter_with_ci_distros)

    idx = 0
    failures = []
    ignored = []

    for idx, (name, path) in enumerate(list_tests(args.SOURCE)):
        try:
            if name in db_ignore:
                report_ignoring(name, "db-ignore", args.verbosity)
                ignored.append(name)
                continue

            test = load_test(name, path, filters)

            if not test:
                report_ignoring(name, "gitlab-ci", args.verbosity)
                ignored.append(name)
                continue

            if args.dry_run:
                continue

            export_test(test, args.TARGET, args.manifest_only)
        except ValueError as e:
            report_failure(name, str(e), args.verbosity)
            failures.append(name)
        else:
            report_import(test, args.verbosity)

    print(f"\n{GREEN}{idx + 1 - len(failures) - len(ignored) }{RESET} tests imported")
    if ignored:
        print(f"{YELLOW}{len(ignored)}{RESET} ignored")
    if failures:
        print(f"{RED}{len(failures)}{RESET} failed")


if __name__ == "__main__":
    main()
